### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by ruanguihua** [wzgiceman/RxjavaRetrofitDemo-master#20]
Process: com.example.retrofit, PID: 25643
                                                                      java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:841)
                                                                       Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.http.HttpEngine
                                                                          at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at com.wzgiceman.rxretrofitlibrary.retrofit_rx.http.cookie.CookieInterceptor.intercept(CookieInterceptor.java:36)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)

**Comment by EGOISTK21** [comment]
com.example.retrofit E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
                                                                      Process: com.example.retrofit, PID: 30780
                                                                      java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                       Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/http/HttpEngine;
                                                                          at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:219)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at com.wzgiceman.rxretrofitlibrary.retrofit_rx.http.cookie.CookieInterceptor.intercept(CookieInterceptor.java:36)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                          at okhttp3.RealCall.execute(RealCall.java:63)
                                                                          at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                          at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
                                                                          at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
                                                                          at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
                                                                          at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10200)
                                                                          at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
                                                                          at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
                                                                          at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
                                                                          at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
                                                                          at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:209)
                                                                          at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                          at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                          at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
                                                                          at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                          at rx.Observable.unsafeSubscribe(Observable.java:10200)
                                                                          at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                          at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                          at java.lang.Thread.run(Thread.java:761) 
com.example.retrofit E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.http.HttpEngine" on path: DexPathList[[zip file "/data/app/com.example.retrofit-1/base.apk", zip file "/data/app/com.example.retrofit-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.retrofit-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.retrofit-1/lib/x86, /system/lib, /vendor/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                          	... 37 more

**Comment by wzgiceman** [comment]
线程问题，检查下是否是回调处理的线程切换导致的

**Comment by wzgiceman** [comment]
change this compile and try agin

 compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
 compile 'com.squareup.retrofit2:retrofit:2.1.0'
 compile 'com.squareup.retrofit2:converter-gson:2.1.0'

**Comment by yezizaiqiutian** [comment]
换成2.1确实能解决崩溃问题,不过,请问楼主为啥呢.....
